<?php
/**
 * Plugin Name:       Custom Gutenberg Blocks
 * Description:       A collection of custom editorial blocks for Sport News.
 * Version:           1.0.0
 * Requires at least: 6.7
 * Requires PHP:      7.4
 * Author:            Your Name
 * Text Domain:       custom-Gutenberg-block
 *
 * @package CustomGutenbergBlocks
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

/**
 * Registers the blocks using the manifest file generated by wp-scripts.
 * This handles both your original block and the new custom-search block.
 */
function cdb_register_all_custom_blocks() {
    $manifest_path = __DIR__ . '/build/blocks-manifest.php';

    // Check if the manifest exists (it is created when you run npm start)
    if ( ! file_exists( $manifest_path ) ) {
        return;
    }

    $manifest_data = require $manifest_path;

    // Loop through every block folder found in the build directory
    foreach ( array_keys( $manifest_data ) as $block_type ) {
        register_block_type( __DIR__ . "/build/{$block_type}" );
    }
}
add_action( 'init', 'cdb_register_all_custom_blocks' );